summary: Search patch configuration by client
description: Searches for patch configurations by a client.
get:
  tags:
    - patching
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: array
                items:
                  $ref: '#/components/schemas/patching-patchConfig'
              totalResults:
                type: integer
              orderBy:
                type: string
              pageNo:
                type: integer
              pageSize:
                type: integer
              totalPages:
                type: integer
              nextPage:
                type: boolean
              previousPageNo:
                type: integer
              descendingOrder:
                type: boolean
  parameters:
    - schema:
        type: integer
        default: '1'
      in: query
      name: pageNo
    - schema:
        type: integer
        default: '100'
      in: query
      name: pageSize
    - schema:
        type: boolean
        default: 'true'
      in: query
      name: isDescendingOrder
    - schema:
        type: string
        default: job.id
      in: query
      name: sortName
parameters:
  - $ref: '#/components/parameters/tenantId'
