post:
  description: |-
    This endpoint is used to get the service status and to start and stop application services.

    An access token must be generated to use this API.

    Supported services are network, squid, postgresql, vprobe, and ntp.
  tags:
    - agents-gateways
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              Success:
                type: string
          examples:
            example-1:
              value:
                Success: Service Squid Proxy started successfully.
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            service:
              type: string
              description: Name of the service.
              enum:
                - network
                - squid
                - postgresql
                - ntp
            action:
              type: string
              description: 'Action item: status, start, or stop.'
              enum:
                - start
                - stop
                - status
                - restart
          required:
            - service
            - action
        examples:
          example-1:
            value:
              service: squid
              action: start
    description: ''
