summary: NEEDS summary
description:
post:
  summary: Assign custom attributes to clients
  description: This endpoint is used to assign custom attributes to clients.
  tags:
    - resource-management
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: './components.yaml#/components/schemas/response'
          examples:
            example-1:
              value:
                failedEntities: {}
                failedCount: 0
                successCount: 2
  requestBody:
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
        examples:
          example-1:
            value:
              - id: client_93
              - id: client_69856
delete:
  summary: Unassign custom attribute from clients
  description: This endpoint is used to unassign custom attribute from clients.
  tags:
    - resource-management
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: './components.yaml#/components/schemas/response'
          examples:
            example-1:
              value:
                FailedEntities: {}
                FailedCount: 0
                SuccessCount: 2
  requestBody:
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
        examples:
          example-1:
            value:
              - id: client_93
              - id: client_69856
parameters:
  - schema:
      type: string
    in: path
    name: varId
    required: true
  - schema:
      type: string
    in: path
    name: attributeId
    required: true
  - schema:
      type: string
    in: path
    name: valueId
    required: true
