# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: 'Perform REST API'
    runs-on: ubuntu-latest
      steps:
        - name: 'Call API'
          uses: indiesdev/curl@v1
          with:
            url: https://api.buddy.works/workspaces/opsramp/projects/docs/pipelines/318801/executions
            method: 'POST'
            accept: 200,201,204
            headers: 
            params:
            body: '{"comment": "Triggered by GitHub push"}'
            timeout: 1000
            bearer-token: ${{ secrets.bearer_token }}
            is_debug: false
